CREATE DATABASE IF NOT EXISTS smart_bake_hub;
USE smart_bake_hub;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'staff', 'customer') DEFAULT 'customer',
    status ENUM('active', 'inactive') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image_url VARCHAR(255),
    availability ENUM('available', 'out_of_stock') DEFAULT 'available',
    discount_percentage DECIMAL(5, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Insert default admin user (Password: admin123 -> you should hash this in production, but for seed we will create it via API or insert hash directly)
-- Hash for 'admin123' using bcrypt with salt rounds 10 is '$2a$10$w1H3jY1/C1j3Z3/Y1/C1j.qK1/C1j3Z3/Y1/C1j3Z3/Y1/C1j3Z3/Y' (Mock hash)
-- Actual bcrypt hash for admin123 is usually generated by the app. I will create a seed script instead of inserting raw SQL for user.

-- Seed some categories
INSERT INTO categories (name, description) VALUES
('Bakery Products', 'Freshly baked breads and buns'),
('Meals', 'Delicious breakfast, lunch, and dinner meals'),
('Beverages', 'Hot and cold drinks'),
('Cakes', 'Custom and ready-made cakes for all occasions')
ON DUPLICATE KEY UPDATE name=name;

-- Create menus table
CREATE TABLE IF NOT EXISTS menus (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_id INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    status ENUM('active', 'inactive') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Create menu_products junction table (many-to-many relationship)
CREATE TABLE IF NOT EXISTS menu_products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    menu_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    UNIQUE KEY unique_menu_product (menu_id, product_id)
);

-- Sample products inserts (can be run if table is empty)
-- Uncomment to populate with sample data
/*
SET @cakes_id = (SELECT id FROM categories WHERE name = 'Cakes' LIMIT 1);
SET @bakery_id = (SELECT id FROM categories WHERE name = 'Bakery Products' LIMIT 1);
SET @meals_id = (SELECT id FROM categories WHERE name = 'Meals' LIMIT 1);
SET @beverages_id = (SELECT id FROM categories WHERE name = 'Beverages' LIMIT 1);

INSERT IGNORE INTO products (category_id, name, description, price, image_url, availability, discount_percentage)
VALUES
(@cakes_id, 'Chocolate Cake', 'Rich chocolate cake with ganache topping', 1200.00, '/uploads/chocolate-cake.jpg', 'available', 0),
(@cakes_id, 'Vanilla Cupcake', 'Classic vanilla cupcake with buttercream', 250.00, '/uploads/vanilla-cupcake.jpg', 'available', 10),
(@bakery_id, 'Butter Croissant', 'Flaky French butter croissant', 180.00, '/uploads/butter-croissant.jpg', 'available', 0),
(@bakery_id, 'Sourdough Bread', 'Artisan sourdough with crispy crust', 350.00, '/uploads/sourdough-bread.jpg', 'available', 0),
(@bakery_id, 'Whole Wheat Bread', 'Nutritious whole wheat bread', 280.00, '/uploads/whole-wheat-bread.jpg', 'available', 5),
(@cakes_id, 'Strawberry Tart', 'Fresh strawberry tart with custard filling', 450.00, '/uploads/strawberry-tart.jpg', 'available', 0),
(@bakery_id, 'Croissant Pack (6)', 'Pack of 6 fresh croissants', 900.00, '/uploads/croissant-pack.jpg', 'available', 15),
(@cakes_id, 'Red Velvet Cake', 'Elegant red velvet cake with cream cheese frosting', 1500.00, '/uploads/red-velvet-cake.jpg', 'available', 0),
(@meals_id, 'Chicken Sandwich', 'Grilled chicken sandwich with fresh vegetables', 350.00, '/uploads/chicken-sandwich.jpg', 'available', 0),
(@meals_id, 'Egg & Cheese Breakfast', 'Fresh egg and cheese breakfast plate', 280.00, '/uploads/egg-cheese-breakfast.jpg', 'available', 10),
(@beverages_id, 'Iced Coffee', 'Cold brew coffee with ice', 250.00, '/uploads/iced-coffee.jpg', 'available', 0),
(@beverages_id, 'Hot Chocolate', 'Creamy hot chocolate', 200.00, '/uploads/hot-chocolate.jpg', 'available', 5),
(@cakes_id, 'Carrot Cake', 'Moist carrot cake with cream cheese frosting', 1100.00, '/uploads/carrot-cake.jpg', 'out_of_stock', 0),
(@meals_id, 'Veg Pasta', 'Fresh vegetable pasta with light sauce', 320.00, '/uploads/veg-pasta.jpg', 'available', 0),
(@bakery_id, 'Chocolate Donut', 'Soft chocolate donut with glaze', 120.00, '/uploads/chocolate-donut.jpg', 'available', 20);
*/
